mod engine;
pub mod events;
mod registry;
mod schema;
mod types;
mod user_notification;

pub use events::session_start::SessionStartOutcome;
pub use events::session_start::SessionStartRequest;
pub use events::session_start::SessionStartSource;
pub use events::stop::StopOutcome;
pub use events::stop::StopRequest;
pub use registry::Hooks;
pub use registry::HooksConfig;
pub use registry::command_from_argv;
pub use schema::write_schema_fixtures;
pub use types::Hook;
pub use types::HookApprovalRequest;
pub use types::HookEvent;
pub use types::HookEventAfterAgent;
pub use types::HookEventAfterApprovalRequested;
pub use types::HookEventAfterElicitationRequested;
pub use types::HookEventAfterInputRequested;
pub use types::HookEventAfterToolUse;
pub use types::HookPayload;
pub use types::HookResponse;
pub use types::HookResult;
pub use types::HookToolInput;
pub use types::HookToolInputLocalShell;
pub use types::HookToolKind;
pub use user_notification::legacy_notify_json;
pub use user_notification::notify_hook;
